"use client"

import { useEffect, useState } from "react"
import { useSession } from "next-auth/react"
import { useRouter } from "next/navigation"
import { AppShell } from "@/components/layout/app-shell"
import { Button } from "@/components/ui/button"
import { Loader2, Calendar, Clock, Target, BookOpen, Sparkles, ChevronDown, ChevronUp, Brain, BarChart3, CheckCircle2 } from "lucide-react"
import Link from "next/link"

interface StudyPlanDay {
  day: number
  focus: string
  topics: string[]
  hours: number
  tasks: string[]
}

interface StudyPlanData {
  id: string
  title: string
  description: string
  planData: { title: string; description: string; days: StudyPlanDay[] }
  startDate: string
  endDate: string
  isAIGenerated: boolean
  createdAt: string
}

export default function StudyPlansPage() {
  const { data: session, status } = useSession()
  const router = useRouter()
  const [plans, setPlans] = useState<StudyPlanData[]>([])
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [expandedPlan, setExpandedPlan] = useState<string | null>(null)
  const [expandedDay, setExpandedDay] = useState<number | null>(null)
  const [duration, setDuration] = useState<7 | 15 | 30>(7)
  const [hoursPerDay, setHoursPerDay] = useState(4)

  useEffect(() => {
    if (status === "unauthenticated") router.push("/login")
    if (status === "authenticated") loadPlans()
  }, [status, router])

  const loadPlans = async () => {
    try {
      const res = await fetch("/api/ai/study-plan")
      if (res.ok) {
        const data = await res.json()
        setPlans(data.plans ?? [])
      }
    } catch {
      // silent
    }
    setLoading(false)
  }

  const generatePlan = async () => {
    setGenerating(true)
    try {
      const res = await fetch("/api/ai/study-plan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ durationDays: duration, availableHoursPerDay: hoursPerDay }),
      })
      if (res.ok) {
        await loadPlans()
      }
    } catch {
      // silent
    }
    setGenerating(false)
  }

  if (loading) {
    return (
      <AppShell>
        <div className="flex h-[60vh] items-center justify-center">
          <Loader2 className="h-10 w-10 animate-spin text-violet-400" />
        </div>
      </AppShell>
    )
  }

  return (
    <AppShell>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">AI Study Plans</h1>
            <p className="text-sm text-muted-foreground">Personalized plans generated by AI based on your performance</p>
          </div>
        </div>

        <div className="rounded-2xl border border-violet-500/20 bg-gradient-to-br from-violet-500/5 to-blue-500/5 p-5">
          <div className="flex items-center gap-3 mb-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-violet-500 to-blue-500">
              <Sparkles className="h-5 w-5 text-white" />
            </div>
            <div>
              <h2 className="font-semibold">Generate New Study Plan</h2>
              <p className="text-xs text-muted-foreground">AI analyzes your weak topics and creates a tailored plan</p>
            </div>
          </div>
          <div className="flex flex-wrap gap-3 items-end">
            <div>
              <label className="text-xs font-medium text-muted-foreground mb-1 block">Duration</label>
              <div className="flex gap-1">
                {([7, 15, 30] as const).map((d) => (
                  <button
                    key={d}
                    onClick={() => setDuration(d)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors ${
                      duration === d
                        ? "border-violet-500/50 bg-violet-500/10 text-violet-400"
                        : "border-border bg-card text-muted-foreground hover:border-violet-500/30"
                    }`}
                  >
                    {d} days
                  </button>
                ))}
              </div>
            </div>
            <div>
              <label className="text-xs font-medium text-muted-foreground mb-1 block">Hours/day</label>
              <select
                value={hoursPerDay}
                onChange={(e) => setHoursPerDay(Number(e.target.value))}
                className="rounded-lg border border-border bg-card px-3 py-1.5 text-xs font-medium outline-none"
              >
                {[2, 3, 4, 5, 6, 8].map((h) => (
                  <option key={h} value={h}>{h} hrs</option>
                ))}
              </select>
            </div>
            <Button onClick={generatePlan} disabled={generating} className="rounded-xl">
              {generating ? <Loader2 className="h-4 w-4 animate-spin mr-1" /> : <Sparkles className="h-4 w-4 mr-1" />}
              Generate Plan
            </Button>
          </div>
        </div>

        {plans.length === 0 ? (
          <div className="rounded-2xl border border-border bg-card p-12 text-center">
            <Brain className="mx-auto mb-3 h-12 w-12 text-muted-foreground/40" />
            <h3 className="font-semibold text-lg">No study plans yet</h3>
            <p className="text-sm text-muted-foreground mt-1 mb-4 max-w-md mx-auto">
              Generate a personalized AI study plan based on your test performance, weak areas, and target exam.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {plans.map((plan) => {
              const days = plan.planData?.days ?? []
              const isExpanded = expandedPlan === plan.id
              return (
                <div key={plan.id} className="rounded-2xl border border-border bg-card overflow-hidden">
                  <button
                    onClick={() => setExpandedPlan(isExpanded ? null : plan.id)}
                    className="w-full flex items-center justify-between p-5 hover:bg-muted/50 transition-colors"
                  >
                    <div className="flex items-center gap-3 text-left">
                      <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-violet-500/20 to-blue-500/20">
                        <Calendar className="h-5 w-5 text-blue-400" />
                      </div>
                      <div>
                        <h3 className="font-semibold">{plan.title}</h3>
                        <p className="text-xs text-muted-foreground">
                          {new Date(plan.startDate).toLocaleDateString()} - {new Date(plan.endDate).toLocaleDateString()} · {days.length} days
                        </p>
                      </div>
                    </div>
                    {isExpanded ? <ChevronUp className="h-5 w-5 text-muted-foreground" /> : <ChevronDown className="h-5 w-5 text-muted-foreground" />}
                  </button>

                  {isExpanded && (
                    <div className="border-t border-border px-5 py-4 space-y-3">
                      {plan.planData?.description && (
                        <p className="text-sm text-muted-foreground">{plan.planData.description}</p>
                      )}
                      <div className="space-y-2">
                        {days.map((day) => {
                          const isDayExpanded = expandedDay === day.day
                          return (
                            <div key={day.day} className="rounded-xl border border-border bg-muted/30 overflow-hidden">
                              <button
                                onClick={() => setExpandedDay(isDayExpanded ? null : day.day)}
                                className="w-full flex items-center justify-between p-3 hover:bg-muted/50 transition-colors"
                              >
                                <div className="flex items-center gap-3">
                                  <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-blue-500/20 to-purple-500/20 text-xs font-bold">
                                    {day.day}
                                  </div>
                                  <div className="text-left">
                                    <p className="text-sm font-medium">{day.focus}</p>
                                    <p className="text-xs text-muted-foreground flex items-center gap-2">
                                      <Clock className="h-3 w-3" /> {day.hours}h
                                      <Target className="h-3 w-3 ml-1" /> {day.topics.length} topics
                                    </p>
                                  </div>
                                </div>
                                {isDayExpanded ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
                              </button>
                              {isDayExpanded && (
                                <div className="border-t border-border px-3 py-3 space-y-2">
                                  <div>
                                    <p className="text-xs font-semibold text-muted-foreground mb-1">Topics</p>
                                    <div className="flex flex-wrap gap-1">
                                      {day.topics.map((topic, i) => (
                                        <span key={i} className="rounded-full border border-violet-500/20 bg-violet-500/10 px-2 py-0.5 text-[10px] text-violet-400">
                                          {topic}
                                        </span>
                                      ))}
                                    </div>
                                  </div>
                                  <div>
                                    <p className="text-xs font-semibold text-muted-foreground mb-1">Tasks</p>
                                    <div className="space-y-1">
                                      {day.tasks.map((task, i) => (
                                        <div key={i} className="flex items-start gap-2 text-xs text-muted-foreground">
                                          <CheckCircle2 className="h-3 w-3 text-emerald-400 mt-0.5 shrink-0" />
                                          {task}
                                        </div>
                                      ))}
                                    </div>
                                  </div>
                                </div>
                              )}
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        )}
      </div>
    </AppShell>
  )
}
